name: Github Pages


on:
  push:
    branches: [ main ]
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup venv and activate it
      run: python3 -m venv venv/ && source venv/bin/activate
      shell: bash
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Build documentation
      run: make html
      shell: bash
    - name: Upload Pages artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        source: ./build
        destination: ./



  deploy:
    needs: build
    permissions:
      contents: write
      id-token: write
      pages: write

        # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4