name: Github Pages


on:
  push:
    branches: [ main ]
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup venv and activate it
      run: python3 -m venv venv/ && source venv/bin/activate
      shell: bash
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Build documentation
      run: make html
      shell: bash
    - name: Upload the built files to the server using rclone
      run: sudo apt install rclone && 
      shell: bash